// os/batch.c

#include "types.h"
#include "riscv.h"
#include "defs.h"      // For panic()
#include "printf.h"    // For printf()


//this sysmbol is defined in link_app.S(generated by pack.py)
extern char _app_num[];

static uint64 *app_info_ptr;
static uint64 app_num;


//initialize batch system - called once at boot
void batchinit(){
    //_app_num points to teh start of app metadata
    app_info_ptr = (uint64*) _app_num;

    //first values is the number of apps
    app_num = *app_info_ptr;
    app_info_ptr++;

    // Now app_info_ptr points to array of app start addresses:
    // app_info_ptr[0] = app_0_start
    // app_info_ptr[1] = app_1_start
    // app_info_ptr[2] = app_1_end
    // app_info_ptr[3] = app_2_start
    // etc.
    
    printf("Found %d applications\n", app_num);
}

// Get info for app number 'id'
// Returns pointer to [start_addr, end_addr]
uint64* get_app_info(int id) {
    if (id >= app_num) {
        panic("Invalid app id");
    }
    return &app_info_ptr[id];
}

// Get total number of apps
int get_app_num() {
    return app_num;
}